### ISSUE TITLE
Missing Effects Crash the Game

### ISSUE THREAD

**Issue by DancingSnowflake497** [Water-and-Critic/KH3-Rando-GoA#88]
No matter what seed I use, even if enemies, Bosses & party members are not randomized, if I play for a very long time, I would recieve this error message constantly:  Line 177:  Unexpected Concurrency While Adding New Object.  Correct me if I'm wrong but I think it might be missing effects like this:  
![No Lanturns 1](https://user-images.githubusercontent.com/79171557/186551805-fa5722f3-7a8a-4882-bb6f-331ebe88cd09.jpg)
I've been very curious about this error ever since I got the same error but with mod menus but didn't figure it out until June when I noticed effects are actually missing.  When I remove the affected mod from the game, the effects return to normal like the lanterns for example.  Upon playing more with the randomizer, even the Union X part of the Keyblade Graveyard's particle effects were showing less Keyblades than usual.

**Comment by AngieRaye** [comment]
This keeps happening in my seed as well. I can't finish toy box or Kingdom of Corona cause I keep getting the same crash and error message.

**Comment by AngieRaye** [comment]
I gave up, I tried all day to fix it. For some reason Release 1.1.2 works though. But the latest version is broken. Just got to hope it gets fixed in the next update.

**Comment by DancingSnowflake497** [comment]
Update 2:  I tested the GOA with the offline client to create a seed with only bosses & enemies randomized & it turns out it never crashed during my run but the effects are still missing like for example, the fire trail in Olympus was black instead of smoky like it originally was.  I find it very strange as to why the client is more stable than the website.  So I guess for now, I'll use the client to randomize my seeds but I'll still leave this issue open since others are struggling with this as well.
